Feature/header comments
TBD-org/Tesseract pull request #38
Opened 2021-02-20 15:13 UTC by FrancPS

2021-02-20 21:51 UTC, JaimeBea requested changes
Hay varios archivos .mesh y .scene que no hacen falta subir

2021-02-20 22:03 UTC, Jordi-Gil requested changes
Como dice Jaime, eliminar los .mesh y .scene innecesarios

2021-02-20 22:03 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleRender.h
> +	void DrawSceneRecursive(const Quadtree<GameObject>::Node& node, const AABB2D& aabb);	// ??
Hay interrogantes. Quizás estaría bien añadir los comentarios antes, en vez de subir algo con ´??´.  Así evitamos olvidarnos de cambiarlo.

2021-02-20 23:54 UTC, JaimeBea commented on Project/Source/Modules/ModuleRender.h
> +	void DrawSceneRecursive(const Quadtree<GameObject>::Node& node, const AABB2D& aabb);	// ??
No creo que esto sea un problema de momento. Se pueden ir rellenando a medida que los vamos viendo.

2021-02-21 11:53 UTC, FrancPS commented on Project/Source/Modules/ModuleRender.h
> +	void DrawSceneRecursive(const Quadtree<GameObject>::Node& node, const AABB2D& aabb);	// ??
No he conseguido entender el funcionamiento del quadtree al 100% y no queria poner una explicación que no fuese cierta..
Hay un par más por ahí, y no he comentado las clases que hablamos con Jaime que se estaban tocando, ni los panels pq practicamente tienen nada.
Supongo que se puede ir haciendo, sip.

Ya lo subo sin los ficheros, que se me pasó, q estuve haciento pruebas con el playpause y guardados.

2021-02-21 12:16 UTC, JaimeBea approved these changes

2021-02-21 16:16 UTC, Jordi-Gil approved these changes

2021-02-22 14:08 UTC, merged