Focus refactor
TBD-org/Tesseract pull request #42
Opened 2021-02-24 22:59 UTC by FrancPS

2021-02-24 23:06 UTC, Jordi-Gil requested changes

2021-02-24 23:06 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleCamera.cpp
> +	vec modelCenter;
Aunque _vec_ es un _typedef_ de _float3_, quizás es más verboso poner _float3_, ya que más adelante estás haciendo 

modelCenter = _float3_::zero

Entonces, alguien que no haya visto nunca la librería de MathGeoLib, de un vistazo le podría confundir.

Es una chorrada, pero lo digo para que quizás sea más fácil de leer en un vistazo rápido.

2021-02-25 11:08 UTC, FrancPS commented on Project/Source/Modules/ModuleCamera.cpp
> +	vec modelCenter;
hecho

2021-02-25 11:09 UTC, Jordi-Gil approved these changes

2021-02-25 11:20 UTC, JaimeBea requested changes
Has cambiado el funcionamiento del focus con mesh. Reintroduce el código antiguo para el caso de que haya una mesh.

2021-02-25 13:14 UTC, FrancPS commented
> Has cambiado el funcionamiento del focus con mesh. Reintroduce el código antiguo para el caso de que haya una mesh.

No entiendo lo que quieres decir.
Compruebo si el GObj tiene alguna mesh (si tiene mas de una es independiente). Luego lo que seria el lookAt lo hago a traves de la posicion, y la distancia de la camara con el GO a traves de la OBB.
Se entiende que si no hay mesh no hay OBB no¿

2021-02-25 18:24 UTC, JaimeBea commented
El problema es que no estás teniendo en cuenta el aspect ratio de la cámara a la hora de hacer el focus. El código anterior lo tenía en cuenta y ajustaba el modelo para que siempre cupiera en la pantalla.

Lo que propones es mejor en cuanto a rendimiento pero peor en funcionalidad. El rendimiento en este caso no es demasiado importante ya que es una función se va a llamar muy de vez en cuando.

2021-02-25 20:52 UTC, FrancPS commented
> El problema es que no estás teniendo en cuenta el aspect ratio de la cámara a la hora de hacer el focus. El código anterior lo tenía en cuenta y ajustaba el modelo para que siempre cupiera en la pantalla.
No me habia dado cuenta de eso, me has convencido.

> EDIT: He encontrado un segundo problema con el código y es que no estás llamando a la función LookAt, y por tanto no se actualizará el punto de focus de la cámara.
Esq con este approach no hace falta. El comportamiento de la camera en este caso seria como que se posiciona en el mismo origen que el objeto y luego se echa para atràs en la direccion de Front().

Anyway, sí, he notado que aveces los objetos quedan un poco cortados del viewport, así que lo cambio.

2021-02-25 22:29 UTC, FrancPS commented
Hecho.
He añadido más cambios porque no consideraba jerarquas complejas de objectos con mesh y sin mesh anidados.
Ahora ya sí, se verán todos los objetos dentro de la jerarquia, aunque la camera siempre mirará hacia el origen del GameObject padre, que en verdad me parece lo suyo.

No se si darle para que vuelva a revisar Jordi, en casos como este.

2021-02-25 22:46 UTC, Jordi-Gil requested changes

2021-02-25 22:46 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleCamera.cpp
> +		if (child->GetComponent<ComponentMeshRenderer>() != nullptr) {
Porque no usas la función 'HasComponent'? Te ahorras devolver un puntero que no usas y compruebas lo mismo.

2021-02-26 01:38 UTC, FrancPS commented
> Si, eso está bien, pero hay una variable extra de distancia de focus que se actualiza con el otro método y con este método no. Es lo que decide el punto alrededor del que orbitar la cámara.

Otias, vale bueno. Pongo el focusDistance para q se actualice entonces.

2021-02-26 11:41 UTC, JaimeBea approved these changes

2021-02-26 13:20 UTC, Jordi-Gil approved these changes

2021-02-26 13:31 UTC, merged