Implement scene importer
TBD-org/Tesseract pull request #43
Opened 2021-02-25 13:25 UTC by JaimeBea

2021-02-25 16:27 UTC, telmiuse commented
Esta todo bien menos todo el codigo inecesario comentado

2021-02-25 16:28 UTC, telmiuse requested changes
Esta todo bien menos todo el codigo  comentado innecesariamente

2021-02-25 16:32 UTC, JaimeBea commented
> Esta todo bien menos todo el codigo comentado innecesariamente

Es para tener una referencia del código que hay que hacer

2021-02-26 15:52 UTC, jcarlos0305 approved these changes

2021-02-26 19:07 UTC, telmiuse approved these changes

2021-02-26 19:16 UTC, merged