Feature/filesystem
TBD-org/Tesseract pull request #60
Opened 2021-03-07 20:09 UTC by Yonimevicio

new filesystem + filedialog + filedialog implemented in load and save scene + some minor fixes in "new scene" and "quit" dialogs.

2021-03-07 21:53 UTC, Jordi-Gil requested changes
Si hay archivos vacios, como Metadata/0/0 no los subas.

2021-03-07 21:53 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleEditor.cpp
> +		FileDialog::Init("Load scene", false, (AllowedExtensionsFlag::SCENE), "D:\\MASTER\\TBD-Engine\\Game\\Library\\Scenes");
La ruta no puede ser esta, ya que, sino, no funcionará de forma genérica. La ruta debería ser relativa siempre en estos casos.

2021-03-07 21:53 UTC, Jordi-Gil commented on Project/Source/Utils/FileDialog.cpp
> +static std::string title_;
Elimina el _ del final de las variables.

2021-03-08 02:07 UTC, Yonimevicio commented on Project/Source/Utils/FileDialog.cpp
> +static std::string title_;
en teoria estaba hablado con jaime para dejar asi la diferenciación variables internas de externas

2021-03-08 02:08 UTC, Yonimevicio commented on Project/Source/Modules/ModuleEditor.cpp
> +		FileDialog::Init("Load scene", false, (AllowedExtensionsFlag::SCENE), "D:\\MASTER\\TBD-Engine\\Game\\Library\\Scenes");
jajaj es verdad my fault pillare la ruta del game no problem

2021-03-08 13:45 UTC, JaimeBea commented on Project/Source/Utils/FileDialog.cpp
> +static std::string title_;
El _ es para variables locales, pero solo si es necesario para diferenciar. Al menos es como está en el resto del código.

2021-03-08 13:56 UTC, Jordi-Gil commented on Project/Source/Utils/FileDialog.cpp
> +static std::string title_;
Vale, no estaba al tanto de esto.

2021-03-08 14:00 UTC, JaimeBea approved these changes

2021-03-08 17:26 UTC, Yonimevicio commented on Project/Source/Utils/FileDialog.cpp
> +		if (OverrideAlertDialog(GetFileNameAndExtension(selectedPath.c_str()))) {};
uiii eso me lo he dejado

2021-03-08 17:27 UTC, Yonimevicio commented on Project/Source/Utils/FileDialog.cpp
> +std::string FileDialog::UpOneLevel(const char* filePath) {
me lo miro

2021-03-08 17:27 UTC, Yonimevicio commented on Project/Source/Utils/FileDialog.cpp
> +		if (i >= 1) // Ignore '.'
me lo miro

2021-03-09 21:38 UTC, JaimeBea commented on Project/Source/Modules/ModuleEditor.cpp
> +std::string gamePath;
Te falta un static. Si no se puede acceder desde cualquier lado y causará conflictos.

2021-03-09 23:54 UTC, merged