Feature/cu f6ytq3 skybox resource
TBD-org/Tesseract pull request #63
Opened 2021-03-16 16:36 UTC by telmiuse

2021-03-16 16:41 UTC, telmiuse commented
Encotre un fallo

2021-03-18 23:58 UTC, JaimeBea requested changes
Te he hecho unos cuantos comentarios, sobre todo en cuanto a estilo, que hay que revisar.

A parte de esto, ¿es necesario tenerlo como como componente o se podría meter como parte de la escena? Sería más conveniente meterlo como parte de la escena, ya que sólo puede haber 1 a la vez.

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +	}
No entiendo que es esta función

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.h
> +	float skyboxVertices[108] {
- Pon skyboxVertices en el .cpp como const
- Usa clang-format off para formatearlo bien. Hay un ejemplo en el skybox anterior.

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.h
> +	unsigned int skyboxVAO, skyboxVBO;
Separa las variables e inicializalas

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +	//glDeleteTextures(1,textureID); //release from il since we have it in opengl
Comentario de debug

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +	// ilOriginFunc(IL_ORIGIN_LOWER_LEFT);
Comentario de debug

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +void ResourceSkybox::Load(JsonValue jComponent) {
Falta un espacio entre funciones

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +}
No es necesaria new line si la función está vacía

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +ResourceSkybox::ResourceSkybox(UID id, const char* assetFilePath, const char* resourceFilePath)
Falta un new line

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +#include "IL/il.h"
Separa imports de librerías externas de los nuestros

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +
Falta un import de "Utils/Leaks.h" al final

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.h
> +#include <FileSystem/JsonValue.h>
Los includes de librerías van con " a no ser que sean de la librería estándar, como <vector>. Recuerda separar los includes de librerías externas de los de código del engine.

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Components/ComponentSkyBox.h
> +#include <FileSystem/JsonValue.h>
Este include debería sec con comillas y estar con los includes de arriba

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Components/ComponentSkyBox.h
> +#include <string>
Estos includes deberían ir abajo con los include de rapidjson

2021-03-18 23:58 UTC, JaimeBea commented on Project/Source/Components/ComponentSkyBox.cpp
> +#include "Modules/ModuleCamera.h"
Mantén los includes organizados. Mira el code style para saber cómo deberían estar.

2021-03-19 02:09 UTC, telmiuse commented on Project/Source/Components/ComponentSkyBox.cpp
> +	glDepthMask(GL_FALSE); // superfluous
esto es lo que explico Carlos de pintar debajo todo lo demas, como primero se pinta el sky luego se activa el deph

2021-03-19 09:25 UTC, telmiuse commented on Game/Library/Data/13/13540996611125161831
> +    "id": 14721918814191546473,
Jaime, tiene que ser un component, sino no se puede crear desde la UI, ni se le puede llamar al draw en cada frame, si estubiera en la escena. Lo he pensado bastante y hablando con otros compañeros decidimos que era la mejor opción

2021-03-20 18:39 UTC, telmiuse commented on Project/Source/Modules/ModulePrograms.h
> +	unsigned CreateProgram(const char* vertexShaderFilePath, const char* fragmentShaderFilePath);
este no queria meterlo

2021-03-20 18:42 UTC, telmiuse commented on Project/Source/Resources/ResourceSkybox.cpp
> +	//glDeleteTextures(1,textureID); //release from il since we have it in opengl
me gustaria dejar esos comentarios hasta ver si todo funciona, comentare un TODO borrar coments si te parece bien

2021-03-20 19:19 UTC, JaimeBea commented on Project/Source/Resources/ResourceSkybox.cpp
> +	//glDeleteTextures(1,textureID); //release from il since we have it in opengl
Me parece bien. Marca cada comment con un TODO y listo.

2021-03-24 10:39 UTC, closed without merging