Integrate OpenAL library
TBD-org/Tesseract pull request #65
Opened 2021-03-17 18:19 UTC by lowysole

This PR contains changes from:

-  feature/CU-ex6mkw-Integrate_OpenAL

2021-03-17 18:20 UTC, lowysole commented
Note: There is one Leak in develop branch

2021-03-17 21:16 UTC, Jordi-Gil requested changes

2021-03-17 21:16 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleAudio.h
> +#include <string>
¿Para qué necesitas el incluir _string_ e _vector_? No veo que se use en ningún sitio. Solamente veo punteros en los atributos. Y en el .cc no veo que se use

2021-03-17 21:16 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleAudio.cpp
> +	if (!name || alcGetError(openALDevice) != AL_NO_ERROR)
Aunque el _if_ solamente tenga una línea añade los _braces_ _{}_. Me remito a mi comentario en este [Pull Request](https://github.com/TBD-org/Tesseract/pull/41#discussion_r582065456)

2021-03-18 10:44 UTC, lowysole commented on Project/Source/Modules/ModuleAudio.cpp
> +	if (!name || alcGetError(openALDevice) != AL_NO_ERROR)
Agree

2021-03-18 10:45 UTC, lowysole commented on Project/Source/Modules/ModuleAudio.h
> +#include <string>
True, eran de una prueba anterior

2021-03-18 10:48 UTC, Jordi-Gil requested changes

2021-03-18 10:48 UTC, Jordi-Gil commented on Project/Tesseract.vcxproj
> +  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
Creo que falta añadir en Release también la librería

2021-03-18 22:40 UTC, Jordi-Gil approved these changes

2021-03-19 00:17 UTC, JaimeBea approved these changes

2021-03-19 00:17 UTC, JaimeBea commented on Project/Source/Utils/alErrors.h
> +#include "Logging.h"
Falta un new line despues del pragma

2021-03-19 00:17 UTC, JaimeBea commented on Project/Source/Utils/alcErrors.h
> +#include "Logging.h"
Falta un new line despues del pragma

2021-03-19 00:17 UTC, JaimeBea commented on Project/Source/Utils/alcErrors.h
> +#include "AL/alc.h"
Este include va con string e iostream

2021-03-19 00:17 UTC, JaimeBea commented on Project/Source/Utils/alErrors.h
> +#include "AL/al.h"
Este include va con string e iostream

2021-03-19 00:17 UTC, JaimeBea commented on Project/Tesseract.vcxproj
> +    <ClInclude Include="Source\Modules\ModuleAudio.h" />
No se si es porque has editado manualmente el archivo, pero ahora todas las líneas pone que han cambiado. Mira si puedes evitarlo.

2021-03-19 09:31 UTC, lowysole commented on Project/Tesseract.vcxproj
> +    <ClInclude Include="Source\Modules\ModuleAudio.h" />
Ha sido VS, lo checkeo para la proxima

2021-03-19 09:37 UTC, Jordi-Gil approved these changes

2021-03-19 09:42 UTC, merged