Functional resource manager
TBD-org/Tesseract pull request #69
Opened 2021-03-23 16:40 UTC by JaimeBea

2021-03-23 23:27 UTC, devildrake commented on Project/Source/Panels/PanelConsole.cpp
> +	UpdateLogString();
Es posible que esta linea genere memory leaks de alguna manera? me saltan leaks con referencia a llamadas a LOG

2021-03-23 23:27 UTC, devildrake commented on Project/Source/Utils/Logging.h
> +#include <queue>
Este include debería hacerse en el .cpp y no aquí (?)

2021-03-23 23:27 UTC, devildrake commented on Project/Source/Resources/ResourceType.h
> +/* Creating a new resource type:
Esto podría estar en algún tipo de Technical Design Document o algo que esté algo más a la vista, muy útil por ejemplo para Isaac y Guillem en el tema de la creación del FontResource

2021-03-24 13:42 UTC, Jordi-Gil requested changes

2021-03-24 13:42 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleResources.cpp
> +		AssetFolder* newFolder = new AssetFolder(ASSETS_PATH);
Esto está produciendo muchos memory leaks. No se libera nunca el newFolder

2021-03-24 13:48 UTC, Jordi-Gil requested changes

2021-03-24 13:48 UTC, Jordi-Gil commented on Project/Source/Modules/ModulePrograms.cpp
> +unsigned ModulePrograms::CreateProgram(const char* ShaderFilePath) {
Están unificados en un solo fichero

2021-03-24 13:48 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleResources.cpp
> +		resource = new ResourceTexture(id, assetFilePath, resourceFilePath.c_str());
Me saltan muchos memory leaks de estos news.

2021-03-24 13:48 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleResources.cpp
> +		resource = new ResourceTexture(id, assetFilePath, resourceFilePath.c_str());
![image](https://user-images.githubusercontent.com/24542154/112320962-ccea3a80-8caf-11eb-8cb9-7915c68bc39e.png)

2021-03-24 13:48 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleResources.cpp
> +		AssetFolder* newFolder = new AssetFolder(ASSETS_PATH);
![image](https://user-images.githubusercontent.com/24542154/112321084-ec816300-8caf-11eb-93d3-9295716806ad.png)

2021-03-24 13:52 UTC, Jordi-Gil commented on Project/Source/Components/ComponentCamera.cpp
> +	OnTransformUpdate();
Todos los GameObject deberían tener una Transform. Debería ser un componente que no se pudiera quitar.

2021-03-24 14:02 UTC, JaimeBea commented on Project/Source/Components/ComponentBoundingBox.cpp
> +	component->SetLocalBoundingBox(this->localAABB);
El allowMultiple es lo que tú comentas. Se utiliza en lo de Create component desde la UI. El duplicate se usa al duplicar GameObjects, así que en principio es necesario.

2021-03-24 14:04 UTC, JaimeBea commented on Project/Source/Components/ComponentBoundingBox.cpp
> +	CalculateWorldBoundingBox();
Si, es el motivo por el que no quería meter en un principio el Calculate en esta función, pero es mucho más fácil de utilizar así. Si se te ocurre algún nombre mejor estaré encantado de cambiarlo.

2021-03-24 15:32 UTC, Jordi-Gil commented on Project/Source/Components/ComponentMeshRenderer.cpp
> +	ImGui::ResourceSlot<ResourceMesh>("Mesh", &meshId);
Al cambiar el Mesh, en el slot la BoundingBox no se recalcula

2021-03-25 14:53 UTC, JaimeBea commented on Project/Source/Components/ComponentCamera.cpp
> +	OnTransformUpdate();
Esto es algo que se podría hacer. Estoy viendo que hay muchos componentes que acaban necesitando acceso a un transform. Me lo guardo y lo hacemos más adelante.

2021-03-25 14:55 UTC, JaimeBea commented on Project/Source/Components/ComponentMeshRenderer.cpp
> +				ComponentBoundingBox* boundingBox = GetOwner().GetComponent<ComponentBoundingBox>();
Cierto, pero en principio todos los objetos con MeshRenderer deberían tener una BoundingBox. Habría que mirar una mejor manera de hacerlo que no sea que explote el motor. Lo guardo también.

2021-03-25 14:56 UTC, JaimeBea commented on Project/Source/GameObject.h
> +	std::vector<std::pair<ComponentType, UID>> components;
Puede haber varios componentes del mismo tipo.

2021-03-25 14:57 UTC, JaimeBea commented on Project/Source/GameObject.h
> +	void RemoveComponents();
Te lo compro.

2021-03-25 15:02 UTC, JaimeBea commented on Project/Source/Panels/PanelInspector.cpp
> +						if (ImGui::MenuItem("Remove Component")) componentToDelete = component;
Mmm... ¿Es posible que el problema de ImGui con los popups? ¿O es otra cosa?

2021-03-25 15:03 UTC, JaimeBea commented on Project/Source/Modules/ModuleResources.h
> +enum class ResourceEventType {
Esto es algo que hay que unificar. Se mira.

2021-03-25 15:04 UTC, JaimeBea commented on Project/Source/Modules/ModuleScene.cpp
> +	scene->root->Update();
Se trata como GameObject porque lo es. En principio se le pueden añadir componentes como se quiera. No se si unity lo hace de otra manera, pero en principio tal y como está funciona bien.

2021-03-25 15:05 UTC, JaimeBea commented on Project/Source/Panels/PanelConsole.cpp
> +	UpdateLogString();
Es posible. Hay que arreglar los memory leaks una vez se haga el merge.

2021-03-25 15:06 UTC, JaimeBea commented on Project/Source/Resources/ResourceType.h
> +/* Creating a new resource type:
Buena idea.

2021-03-25 15:10 UTC, JaimeBea commented on Project/Source/Modules/ModuleScene.h
>  #include "Utils/Pool.h"
En principio hay que evitar depender de imports dentro de otros imports. Si de repente cambian los imports en ese archivo habrá problemas por todo el proyecto. Entiendo que esto no se puede mantener siempre al 100%, pero hay que intentarlo.

2021-03-25 15:11 UTC, JaimeBea commented on Project/Source/Modules/ModuleResources.cpp
> +		AssetFolder* newFolder = new AssetFolder(ASSETS_PATH);
Los memory leaks los miraremos bien una vez se haya hecho el merge.

2021-03-25 15:11 UTC, JaimeBea commented on Project/Source/Modules/ModuleResources.cpp
> +		resource = new ResourceTexture(id, assetFilePath, resourceFilePath.c_str());
Los memory leaks los miraremos bien una vez se haya hecho el merge.

2021-03-25 15:13 UTC, JaimeBea commented on Project/Source/Components/ComponentMeshRenderer.cpp
> +	ImGui::ResourceSlot<ResourceMesh>("Mesh", &meshId);
Mmm, no había caído en esto. En principio no es algo crítico, así que lo apunto para resolver una vez se haga el merge.

2021-03-25 15:15 UTC, Jordi-Gil commented on Project/Source/Modules/ModuleResources.cpp
> +		resource = new ResourceTexture(id, assetFilePath, resourceFilePath.c_str());
Sí, sí. Estos comentarios los hice antes de la reunión de ayer.

2021-03-25 15:15 UTC, Jordi-Gil approved these changes

2021-03-25 15:16 UTC, JaimeBea commented on Project/Source/Modules/ModuleResources.cpp
> +		resource = new ResourceTexture(id, assetFilePath, resourceFilePath.c_str());
Lo se, lo se. Es para tenerlo por escrito.

2021-03-25 16:54 UTC, devildrake commented on Project/Source/Panels/PanelInspector.cpp
> +						if (ImGui::MenuItem("Remove Component")) componentToDelete = component;
Estuve trasteando con el tema de PushID para ver si era algo de eso pero no lo conseguí hacer funcionar. Uncertain de qué puede ser el problema

2021-03-25 16:56 UTC, devildrake approved these changes

2021-03-25 17:26 UTC, JaimeBea commented on Project/Source/Panels/PanelInspector.cpp
> +						if (ImGui::MenuItem("Remove Component")) componentToDelete = component;
No soy capaz de reproducirlo. Si quieres lo miramos en algún momento.

2021-03-25 17:26 UTC, merged