Feature/player movement cu gx446e
TBD-org/Tesseract pull request #94
Opened 2021-04-11 12:03 UTC by telmiuse

2021-04-11 14:01 UTC, FrancPS requested changes

2021-04-11 14:19 UTC, telmiuse commented on Game/Assets/Scripts/CubeMovement.h
> +	int speed = 10;
perque vols public?

2021-04-11 14:19 UTC, telmiuse commented on Game/Assets/Scripts/aaaa.h
>  };
aaaa. esteia a develop ja pero per jo es pot eliminar

2021-04-11 14:20 UTC, telmiuse commented on Game/Penteract/Penteract.vcxproj
> +    <Tesseract_LibraryPath>M:\Master-UPC\Tesseract\Build\Debug</Tesseract_LibraryPath>
això esta revisat per ell, cada un ha de tenir el seu.

2021-04-11 14:20 UTC, telmiuse commented on Project/Source/Components/UI/ComponentCanvasRenderer.h
> -
es pot eliminar segons m'ha dit el Miguel

2021-04-11 14:20 UTC, telmiuse commented on Project/Source/GameplaySystems.cpp
> +}
no ho entenc

2021-04-11 14:21 UTC, telmiuse commented on Project/Source/GameplaySystems.cpp
> +}
no ho entenc

2021-04-11 14:22 UTC, Jordi-Gil commented on Game/Penteract/Penteract.vcxproj
> +    <Tesseract_LibraryPath>M:\Master-UPC\Tesseract\Build\Debug</Tesseract_LibraryPath>
No subais el .vcxproj / .sln pls. Quitalo del PR

2021-04-11 14:22 UTC, Jordi-Gil commented on Project/Source/Components/UI/ComponentCanvasRenderer.h
> -
Se elimina, no tenía sentido allí en ese .h

2021-04-11 14:28 UTC, telmiuse commented on Game/Assets/Scripts/CubeMovement.h
> +	int speed = 10;
Cada Script ha de ser únic per cada object, per això esta així, no tenim la funcionalitat de què el mateix script detecti a quin object està assossiat

2021-04-11 14:29 UTC, telmiuse commented on Game/Assets/Scripts/PlayerMovement.h
> +	int speed = 10;
No estic tant d'acord amb el fet que sigui pública, és una variable pròpia del objecte, no ha de ser cridada per cap altre objecte per el tant hauria de ser privada.

2021-04-11 16:28 UTC, FrancPS commented on Game/Assets/Scripts/CubeMovement.h
> +	int speed = 10;
Per a poder accedir a la variable des del inspector, quan la funcionalitat estigui
Imitant a Unity, les varibles privades nomes es veuen des de dins del script, i les publiques es poden editar des del engine

2021-04-11 16:32 UTC, FrancPS commented on Project/Source/GameplaySystems.cpp
> +}
el estado IDLE representa un int = 0, por lo tanto un booleano a false.
Los otros 3 estados representan int = 1, 2 y 3, por lo tanto un booleano true.

Digo de tener una funcion generica para los estados UP, DOWN y REPEAT (GetMouseButtons()[button] devuelve 1 2 o 3, convertido a booleano true) y ademas las 3 funciones especificas para cada uno de los 3 estados, que es lo que ya has implementado

2021-04-13 13:32 UTC, JaimeBea approved these changes

2021-04-13 14:11 UTC, Jordi-Gil approved these changes

2021-04-13 14:19 UTC, FrancPS approved these changes

2021-04-13 14:20 UTC, merged